Changed description of caret character in docs
rust-lang/cargo pull request #12209
Opened 2023-05-31 16:01 UTC by gautamprikshit1

2023-05-31 16:36 UTC, weihanglo reviewed
Thanks for being interested in contributing to this project! I guess you're fixing #12112. As a good practice, contributors are encouraged to follow [the process of submitting a PR](https://doc.crates.io/contrib/process/working-on-cargo.html#submitting-a-pull-request) in Cargo Contributor Guide, as well as the guideline in [the pull request template](https://github.com/rust-lang/cargo/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1).

I would suggest providing a minimal description for this pull request.

2023-05-31 16:36 UTC, weihanglo commented on src/doc/src/reference/specifying-dependencies.md
> +`^1.2.3` means the same thing as `1.2.3`, which allows [SemVer]: https://semver.org compatible updates.
```suggestion
For instance, `log = "^1.2.3"` means the same thing as `log = "1.2.3",
which allows [SemVer] compatible updates.
```

2023-05-31 16:38 UTC, weihanglo commented on src/doc/src/reference/specifying-dependencies.md
> +`^1.2.3` means the same thing as `1.2.3`, which allows [SemVer]: https://semver.org compatible updates.
This combines suggestion from me and ehuss in #12112. What do you think?

```suggestion
For instance, `log = "^1.2.3"` means the same thing as `log = "1.2.3",
which allows [SemVer] compatible updates.
```

2023-06-01 07:02 UTC, weihanglo requested changes

2023-06-01 07:02 UTC, weihanglo commented on src/doc/src/reference/specifying-dependencies.md
> +which allows [SemVer]: https://semver.org compatible updates.
The link is unnecessary I believe?

```suggestion
which allows [SemVer] compatible updates.
```

2023-06-01 08:41 UTC, weihanglo approved these changes
Thanks.

I am going to merge this once CI passes. If you manage to squash commits into one before that, feel free to do so.

2023-06-01 09:02 UTC, weihanglo commented
Sorry but no that is not what I meant. I suggested squashing for keeping the git history meaningful. It's not a hard requirement but this PR is better to fit in a single commit.

Some useful resources:

* Here is [an article](https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git) about how git squashes works.
* Here is a [CS course from MIT](https://missing.csail.mit.edu/2020/version-control/) that I found it useful to learn version control system.

BTW, communication is essential in open source project collaboration. Feel free to comment here or ask anything.

2023-06-01 09:13 UTC, gautamprikshit1 commented
I just updated the branch, I will squash the commits soon.
Will join the zulip chat for communication on further issues. I appreciate the resources and feedback.

2023-06-05 09:50 UTC, LingMan commented on src/doc/src/reference/specifying-dependencies.md
>  **Caret requirements** are an alternative syntax for the default strategy,
You're starting a new sentence in the next line, so the comma at the end of this one should be turned into a period.

2023-06-05 16:50 UTC, weihanglo commented
@rustbot author

@gautamprikshit1, when this is ready for the next round of review, use `@rustbot ready` to notify reviews.

2023-06-06 12:15 UTC, gautamprikshit1 commented
@rustbot ready

2023-06-06 12:22 UTC, gautamprikshit1 commented
@weihanglo couldn't squash commits due to the branch updates between commits and hence large number of commits

2023-06-06 14:38 UTC, weihanglo commented
@gautamprikshit1, it seems that you still did it wrong.

d9434e00a62fc145abddc51e86e0cadddd02fa19 is not what LingMan suggests. We probably need to drop that commit. Besides, the commits are still piled up in this pull request. Have you read those aformentioned materials https://github.com/rust-lang/cargo/pull/12209#issuecomment-1571642607? They should provide a decent amount of understanding :)

2023-06-06 17:50 UTC, LingMan commented
@gautamprikshit1 My suggestion was to change `, For` to `. For`, not `, which` to `. which`. It's one line earlier.

2023-08-25 08:53 UTC, weihanglo commented
Due to inactivity and to reduce the review queue, this will be closed shortly. The patch should be relatively easy. Feel free to submit a new one when the above Git and grammar issues are resolved.

2023-08-25 08:53 UTC, closed without merging