Fixes error count display is different when there's only one error left
rust-lang/cargo pull request #12484
Opened 2023-08-12 13:15 UTC by adrianEffe

### What does this PR try to resolve?

When there's only 1 error left, the number 1 appears in the output so that it scans the same as the output when there's more than 1 error, so:

```
error: could not compile `crate` (lib test) due to 1 previous error
``` 
instead of the current:
```
error: could not compile `crate` (lib test) due to a previous error
``` 

Fixes #12390

2023-08-12 20:20 UTC, weihanglo reviewed
Looks good. Thanks!

Let's give rustc folks a bit more time to review on their side.

2023-08-12 20:20 UTC, weihanglo approved these changes

2023-11-29 16:36 UTC, weihanglo requested changes
Something went wrong in the git merge. You might want to start over and cherry-pick the latest few commits/

2023-11-29 16:54 UTC, adrianEffe commented
@Nilstrieb and @WaffleLapkin helped us get [#118138](https://github.com/rust-lang/rust/pull/118138) over the line for rustc

2023-11-29 17:19 UTC, weihanglo approved these changes
Thank you, @adrianEffe. Let us merge this :)

2023-11-29 18:14 UTC, Nilstrieb commented
> @Nilstrieb and @WaffleLapkin helped us get [#118138](https://github.com/rust-lang/rust/pull/118138) over the line for rustc

haha, this PR is a lot simpler, nice :)

2023-11-29 18:37 UTC, weihanglo commented
@bors r+

2023-11-29 19:52 UTC, merged